spring:
  application:
    name: server
server:
  address: 0.0.0.0
  port: 8080
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: passwd
#    key-store-type: PKCS12
#    key-alias: spring
#    key-password: passwd